import { Capture,Playback } from './audio.js';
type Side='doctor'|'patient';
type Patient={name:string;patientId:string;age:string;gender:string;phone:string;emergencyContact:string;allergies:string;conditions:string;currentMedications:string;reasonForVisit:string;department:string;room:string;consent:true};
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const value=(id:string)=>$<HTMLSelectElement>(id).value;
const disable=(id:string,disabled:boolean)=>($<HTMLButtonElement>(id).disabled=disabled);
const capture:Partial<Record<Side,Capture>>={};const playback={doctor:new Playback(),patient:new Playback()};const seq={doctor:0,patient:0};
let socket:WebSocket|undefined,active=false,starting=false,sessionId='',reportToken='',startTime=0,demoStep=0,mode='live';let turns:any[]=[];let sessionLanguage='hi',sessionPatient:Patient|undefined;let ending=false,reviewDirty=false;const lastCaption:Record<Side,number>={doctor:0,patient:0};const receivedChunks:Record<Side,number>={doctor:0,patient:0};const attention:Record<Side,{urgency:string;source:string}>={doctor:{urgency:'normal',source:'manual'},patient:{urgency:'normal',source:'manual'}};
function notice(text:string,info=false){$('notice').textContent=text;$('notice').hidden=!text;$('notice').classList.toggle('info',info);}
function send(event:object){if(socket?.readyState!==WebSocket.OPEN)throw new Error('Connection unavailable');if(socket.bufferedAmount>256000)throw new Error('Connection is too slow. Stop and reconnect.');socket.send(JSON.stringify(event));}
function resetCapture(){for(const side of ['doctor','patient'] as const){capture[side]?.stop();delete capture[side];$(side+'-wave').classList.remove('active');$(side+'-state').textContent='Microphone stopped';$(side+'-talk').textContent=`◉ Start ${side} microphone`;$(side+'-talk').classList.remove('recording');}}
function controls(){for(const id of ['language','mode','pin','start'])disable(id,active||starting);document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('.patient-intake input,.patient-intake textarea').forEach(el=>el.disabled=active||starting);for(const id of ['urgent','clear'])disable(id,!active||ending);disable('end',(!active&&!starting)||ending);for(const side of ['doctor','patient']){disable(side+'-talk',!active||ending||mode!=='live');disable(side+'-switch',!active||ending||mode!=='live');$(side+'-switch').textContent=capture[side as Side]?'■ Pause '+side+' microphone':'Speak as '+side;$(side+'-switch').classList.toggle('recording',!!capture[side as Side]);disable(side+'-mic',!!capture[side as Side]);}disable('demo-next',!active||ending||mode!=='demo'||demoStep>=4);$('rehearsal').hidden=value('mode')!=='demo';$('session-status').textContent=ending?'Ending session…':starting?'Connecting to interpreter…':active?(mode==='live'?'Session active · live interpretation':'Session active · scripted rehearsal'):'Enter patient details, then start';for(const id of ['patient-report','clinical-report','transcript-report','json-report'])disable(id,turns.length===0||!reportToken);}
function field(id:string){return $<HTMLInputElement|HTMLTextAreaElement>(id).value.trim();}
function patient():Patient|undefined{const name=field('patient-name'),patientId=field('patient-id'),reasonForVisit=field('reason'),department=field('department'),consent=$<HTMLInputElement>('consent').checked;if(!name||!patientId||!reasonForVisit||!department||!consent){notice('Complete patient name, ID, reason for visit, department and consent before starting.');document.querySelector<HTMLElement>('.patient-intake')?.scrollIntoView({behavior:'smooth'});return;}return {name,patientId,age:field('patient-age'),gender:field('patient-gender'),phone:field('patient-phone'),emergencyContact:field('emergency-contact'),allergies:field('allergies'),conditions:field('conditions'),currentMedications:field('current-medications'),reasonForVisit,department,room:field('room'),consent:true};}
const lines=(id:string)=>$<HTMLTextAreaElement>(id).value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
function reportReview(){return {chiefComplaint:$<HTMLTextAreaElement>('review-chief').value.trim(),patientHighlights:lines('review-highlights'),doctorPlan:lines('review-plan'),attentionItems:lines('review-attention'),unresolved:lines('review-unresolved'),reviewed:$<HTMLInputElement>('reviewed').checked,reviewedBy:field('reviewed-by')};}
function renderClinical(summary:any){if(reviewDirty)return;$<HTMLTextAreaElement>('review-chief').value=summary.chiefComplaint||'';$<HTMLTextAreaElement>('review-highlights').value=(summary.patientHighlights||[]).map((x:any)=>x.text).join('\n');$<HTMLTextAreaElement>('review-attention').value=(summary.attentionItems||[]).map((x:any)=>x.text).join('\n');$<HTMLTextAreaElement>('review-plan').value=(summary.doctorPlan||[]).map((x:any)=>`[${x.category}] ${x.text}`).join('\n');$<HTMLTextAreaElement>('review-unresolved').value=(summary.unresolved||[]).join('\n');}
function signal(urgency:string,source='manual'){$('attention').className='attention card '+urgency;$('attention-summary').textContent=urgency==='high'?'⚑ Attention needed · confirm with patient':urgency==='elevated'?'⚑ Elevated vocal intensity':'Automatic attention · no active flag';$('attention-summary').className=urgency;$('signal-title').textContent=urgency==='high'?'Attention needed':urgency==='elevated'?'Elevated intensity':'Conversation steady';$('signal-icon').textContent=urgency==='normal'?'✓':'!';$('signal-description').textContent=urgency==='normal'?'No attention flag is currently active.':`Flagged by ${source}. Confirm the speaker’s message directly.`;document.querySelectorAll('.signal-scale span').forEach((s,i)=>(s as HTMLElement).style.background=i<=(urgency==='high'?2:urgency==='elevated'?1:0)?(urgency==='high'?'#cc7660':urgency==='elevated'?'#d4b065':'#8bad70'):'#edf1e8');}
function renderTurn(turn:any){
 if(turns.some(t=>t.id===turn.id))return;turns.push(turn);if(turns.length===1)$('turns').replaceChildren();
 const article=document.createElement('article');article.className='turn';const meta=document.createElement('div');meta.className='turn-meta';const name=document.createElement('strong');name.textContent=turn.speaker;const time=document.createElement('span');time.textContent=new Date(turn.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});meta.append(name,time);if(turn.urgency!=='normal'){const flag=document.createElement('span');flag.className=turn.urgency;flag.textContent=turn.urgency.toUpperCase()+' ATTENTION';meta.append(flag);}
 const original=document.createElement('p');original.className='original';original.textContent=turn.original_text;original.lang=turn.speaker==='patient'?sessionLanguage:'en';const translated=document.createElement('p');translated.textContent=turn.translated_text;translated.lang=turn.speaker==='doctor'?sessionLanguage:'en';article.append(meta,original,translated);$('turns').append(article);$('turns').scrollTop=$('turns').scrollHeight;$('partial').textContent='';$('turn-count').textContent=`${turns.length} translated turns`;$('export').removeAttribute('disabled');$(turn.speaker+'-caption').textContent=turn.original_text;$(turn.speaker+'-live-original').textContent=turn.original_text;$(turn.speaker+'-live-translation').textContent=turn.translated_text;
 if(mode==='demo'&&$<HTMLInputElement>('sound').checked&&'speechSynthesis' in window){const speech=new SpeechSynthesisUtterance(turn.translated_text);speech.lang=turn.speaker==='patient'?'en-IN':sessionLanguage+'-IN';speechSynthesis.speak(speech);}
}
async function onEvent(event:any){
 if(event.type==='session_started'){active=true;starting=false;sessionId=event.sessionId;reportToken=event.reportToken;startTime=Date.now();$('session-id').textContent='SESSION '+sessionId.slice(0,8).toUpperCase();$('connection').innerHTML='<i></i> '+(mode==='demo'?'Rehearsal connected':'Live connection');$('connection').classList.add('live');notice(mode==='demo'?'Guided rehearsal uses scripted translations and your browser’s available voices. Switch to Live microphone for Gemini interpretation.':'Live session ready. Allow microphone access; patient listening starts now.',true);controls();if(mode==='live'){$('guide').hidden=true;$('help').setAttribute('aria-expanded','false');void startMicrophone('patient');}}
 if(event.type==='transcript_update'){const side=event.speaker as Side;lastCaption[side]=Date.now();$(side+'-caption').textContent=event.text;$(side+'-live-original').textContent=event.text;$(side+'-state').textContent=event.final?'Phrase recognized':'Transcribing speech…';}
 if(event.type==='translation_update'){$(event.speaker+'-live-translation').textContent=event.text;$('partial').textContent=event.speaker+' · translating…';}
 if(event.type==='audio_received'){const side=event.speaker as Side;receivedChunks[side]=event.chunks;if(capture[side])$(side+'-state').textContent=event.level>.01?'Voice reaching server · '+event.chunks+' chunks':'Microphone connected · waiting for audible speech';}
 if(event.type==='translated_turn')renderTurn(event);
 if(event.type==='clinical_update')renderClinical(event.summary);
 if(event.type==='urgency_update'){attention[event.speaker as Side]={urgency:event.urgency,source:event.source};const rank:Record<string,number>={normal:0,elevated:1,high:2};const highest=Object.values(attention).sort((a,b)=>rank[b.urgency]-rank[a.urgency])[0];signal(highest.urgency,highest.source);}
 if(event.type==='interrupt'){playback.doctor.stop();playback.patient.stop();window.speechSynthesis?.cancel();}
 if(event.type==='audio_output'&&active&&$<HTMLInputElement>('sound').checked){const recipient=event.speaker==='doctor'?'patient':'doctor';await playback[recipient].play(event.audio,event.mime_type);}
 if(event.type==='error'||event.type==='provider_unavailable')notice(event.message);
 if(event.type==='session_ended'){active=false;ending=false;resetCapture();controls();notice(`Session complete · ${event.turnCount} translated turns. Your transcript is ready to export.`,true);}
}
$('start').onclick=async()=>{
 const intake=patient();if(!intake)return;sessionPatient=intake;starting=true;ending=false;mode=value('mode');sessionLanguage=value('language');controls();notice('Connecting…',true);
 try{await Promise.all([playback.doctor.unlock(),playback.patient.unlock()]);if(ending){starting=false;ending=false;controls();return;}turns=[];sessionId='';reportToken='';reviewDirty=false;$<HTMLInputElement>('reviewed').checked=false;$<HTMLInputElement>('reviewed-by').value='';for(const id of ['review-chief','review-highlights','review-attention','review-plan','review-unresolved'])$<HTMLTextAreaElement>(id).value='';$('review-state').textContent='UNREVIEWED';$('review-state').classList.remove('confirmed');$('session-id').textContent='No active session';$('partial').textContent='';$('timer').textContent='00:00';attention.doctor={urgency:'normal',source:'manual'};attention.patient={urgency:'normal',source:'manual'};demoStep=0;seq.doctor=0;seq.patient=0;$('turns').replaceChildren();$('turn-count').textContent='0 translated turns';$('demo-step').textContent='GUIDED REHEARSAL · 0 / 4';signal('normal');for(const side of ['doctor','patient'] as const){lastCaption[side]=0;receivedChunks[side]=0;$(side+'-live-original').textContent='Waiting for '+side+' speech…';$(side+'-live-translation').textContent='Translation appears here…';}
  const configured=(window as any).PULSELINE_GATEWAY as string|undefined;const url=configured?new URL('/ws',configured):new URL('/ws',location.href);url.protocol=url.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(url);
  const timeout=setTimeout(()=>{if(starting){notice('Connection timed out. Check the gateway and try again.');socket?.close();}},110000);
  socket.onopen=()=>send({type:'session_start',doctorLanguage:'en',patientLanguage:sessionLanguage,mode,patient:sessionPatient,pin:value('pin')});
  socket.onmessage=e=>{void onEvent(JSON.parse(e.data)).catch(()=>notice('Audio could not play. Check your output device.'));};
  socket.onerror=()=>notice('Could not connect to the gateway. Check your connection and try again.');
  socket.onclose=e=>{clearTimeout(timeout);const wasActive=active;active=false;starting=false;ending=false;resetCapture();playback.doctor.stop();playback.patient.stop();window.speechSynthesis?.cancel();$('connection').classList.remove('live');$('connection').innerHTML='<i></i> '+(turns.length?'Session ended':'Disconnected');controls();if(e.code!==1000&&e.code!==1005)notice(`Connection ended: ${e.reason||'network interruption'}. Start a new session; the current transcript can still be exported.`);else if(wasActive)notice('Session disconnected. Start a new session to continue.');};
 }catch(error){starting=false;controls();notice(error instanceof Error?error.message:'Unable to start');}
};
function stopMicrophone(side:Side){capture[side]?.stop();delete capture[side];if(active&&!ending)try{send({type:'audio_end',mic:side});}catch{}$(side+'-talk').textContent='◉ Start '+side+' microphone';$(side+'-talk').classList.remove('recording');$(side+'-wave').classList.remove('active');$(side+'-state').textContent='Microphone paused';controls();}
async function startMicrophone(side:Side){
 if(!active||ending||capture[side])return;
 const other=side==='doctor'?'patient':'doctor';if(capture[other]&&value(side+'-mic')===value(other+'-mic'))stopMicrophone(other);
 const mic=new Capture();capture[side]=mic;disable(side+'-talk',true);$(side+'-state').textContent='Waiting for microphone permission…';
 try{await mic.start(value(side+'-mic'),(data,level)=>{if(!active||ending||capture[side]!==mic)return;try{send({type:'audio_chunk',mic:side,seq:seq[side]++,data});$(side+'-wave').classList.toggle('active',level>.01);}catch(error){stopMicrophone(side);notice((error as Error).message);}});if(!active||ending||capture[side]!==mic){mic.stop();return;}$(side+'-talk').textContent='■ Stop '+side+' microphone';$(side+'-talk').classList.add('recording');$(side+'-state').textContent='Listening · waiting for speech';$('session-help').textContent='Listening to '+side+'. Read Heard and Translation below. Tap the other microphone to switch speakers.';notice('Listening to '+side+'. Speak naturally, then pause briefly. Use headphones to avoid feedback.',true);
 const count=receivedChunks[side],caption=lastCaption[side];setTimeout(()=>{if(active&&capture[side]===mic&&lastCaption[side]===caption)notice(receivedChunks[side]===count?'No audio has reached the server. Check microphone permission and your selected input.':'Audio is reaching the server, but no speech has been recognized yet. Check the selected speaker/language and microphone level.');},12000);
 }catch(error){mic.stop();if(capture[side]===mic)delete capture[side];$(side+'-state').textContent='Microphone unavailable';notice('Microphone unavailable: '+(error instanceof Error?error.message:'permission denied')+'. Allow access and press Start microphone.');}finally{controls();}
}
for(const side of ['doctor','patient'] as const){
 for(let i=0;i<31;i++){const bar=document.createElement('i');bar.style.height=(4+Math.sin(i*.8)**2*(20-Math.abs(15-i)))+'px';$(side+'-wave').append(bar);}
 $(side+'-talk').onclick=()=>{if(capture[side])stopMicrophone(side);else void startMicrophone(side);};
 $(side+'-switch').onclick=()=>{if(capture[side])stopMicrophone(side);else void startMicrophone(side);};
 $(side+'-output').onchange=()=>{void playback[side].sink(value(side+'-output')).catch(e=>notice(e.message));};
}
$('devices').onclick=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop());const devices=await navigator.mediaDevices.enumerateDevices();for(const side of ['doctor','patient'])for(const [kind,suffix] of [['audioinput','mic'],['audiooutput','output']]){const select=$<HTMLSelectElement>(side+'-'+suffix),previous=select.value;select.replaceChildren(new Option('Default '+(suffix==='mic'?'microphone':'speaker'),''));devices.filter(d=>d.kind===kind&&d.deviceId!=='default').forEach((d,i)=>select.add(new Option(d.label||`${suffix} ${i+1}`,d.deviceId)));select.value=previous;}notice('Audio devices refreshed.',true);}catch{notice('Allow microphone access to list your audio devices.');}};
$('language').onchange=()=>{const hi=value('language')==='hi';$('patient-language').textContent=hi?'Hindi · HI':'Telugu · TE';$('patient-caption').textContent=hi?'हर बात समझी जाए।':'ప్రతి మాట అర్థం కావాలి.';$('patient-caption').lang=value('language');};
$('demo-next').onclick=()=>{try{send({type:'demo_turn',index:demoStep});demoStep++;$('demo-step').textContent=`GUIDED REHEARSAL · ${demoStep} / 4`;controls();}catch(e){notice((e as Error).message);}};
$('urgent').onclick=()=>send({type:'flag_urgent',speaker:'patient',urgency:'high'});
$('clear').onclick=()=>{for(const speaker of ['doctor','patient'])send({type:'flag_urgent',speaker,urgency:'normal'});};
$('end').onclick=()=>{ending=true;resetCapture();playback.doctor.stop();playback.patient.stop();window.speechSynthesis?.cancel();if(starting){socket?.close(1000,'Cancelled');}else{try{send({type:'session_end'});}catch{socket?.close();}}controls();};
$('help').onclick=()=>{const hidden=!$('guide').hidden;$('guide').hidden=hidden;$('help').setAttribute('aria-expanded',String(!hidden));};
$('mode').onchange=()=>{mode=value('mode');controls();};
$('sound').onchange=()=>{if(!$<HTMLInputElement>('sound').checked){playback.doctor.stop();playback.patient.stop();window.speechSynthesis?.cancel();}};
for(const id of ['review-chief','review-highlights','review-attention','review-plan','review-unresolved','reviewed-by'])$(id).addEventListener('input',()=>reviewDirty=true);
$<HTMLInputElement>('reviewed').onchange=()=>{reviewDirty=true;const confirmed=$<HTMLInputElement>('reviewed').checked;$('review-state').textContent=confirmed?'CLINICIAN REVIEWED':'UNREVIEWED';$('review-state').classList.toggle('confirmed',confirmed);};
async function downloadReport(type:'patient'|'clinical'|'transcript'|'json'){
 if(!sessionId||!reportToken)return;const review=reportReview();if(type==='clinical'&&!review.reviewed)notice('Clinical handoff is marked UNREVIEWED. Confirm the review checkbox when a clinician has checked it.',true);
 const actions=document.querySelector('.report-actions')!;actions.classList.add('busy');notice('Generating protected report…',true);
 try{const response=await fetch('/api/reports',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type,sessionId,reportToken,review})});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||'Report generation failed');const disposition=response.headers.get('content-disposition')||'';const name=disposition.match(/filename="([^"]+)"/)?.[1]||`PulseLine_${type}.${type==='json'?'json':'pdf'}`;const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice(`${name} generated.`,true);}catch(error){notice(error instanceof Error?error.message:'Report generation failed.');}finally{actions.classList.remove('busy');}
}
$('patient-report').onclick=()=>void downloadReport('patient');$('clinical-report').onclick=()=>void downloadReport('clinical');$('transcript-report').onclick=()=>void downloadReport('transcript');$('json-report').onclick=()=>void downloadReport('json');
setInterval(()=>{if(active){const elapsed=Math.floor((Date.now()-startTime)/1000);$('timer').textContent=String(Math.floor(elapsed/60)).padStart(2,'0')+':'+String(elapsed%60).padStart(2,'0');}},1000);
window.addEventListener('beforeunload',()=>{resetCapture();socket?.close();});
fetch('/api/config').then(r=>r.json()).then(config=>{$('pin-label').hidden=!config.pinRequired;if(!config.liveAvailable){($<HTMLSelectElement>('mode').querySelector('option[value=live]') as HTMLOptionElement).disabled=true;$<HTMLSelectElement>('mode').value='demo';mode='demo';controls();notice('Rehearsal is ready. Live interpretation becomes available when the server’s Gemini key is configured.',true);}}).catch(()=>notice('Gateway configuration unavailable. Check that the server is running.'));
controls();
