import { Capture,Playback } from './audio.js';
type Side='doctor'|'patient';
type Patient={fullName:string;patientId:string;birthOrAge:string;gender:string;language:'hi'|'te';phone:string;emergencyContact:string;allergies:string;conditions:string;medications:string;reasonForVisit:string;doctorDepartment:string;consent:true;room:string};
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const value=(id:string)=>$<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>(id).value.trim();
const disable=(id:string,disabled:boolean)=>($<HTMLButtonElement>(id).disabled=disabled);
const capture:Partial<Record<Side,Capture>>={},playback={doctor:new Playback(),patient:new Playback()},seq={doctor:0,patient:0};
let socket:WebSocket|undefined,active=false,starting=false,sessionId='',startTime=0,demoStep=0,mode='demo',patient:Patient|undefined,turns:any[]=[],facts:any[]=[],flags:any[]=[],reviewRecord:any,historyLoad=0,captureMutedUntil=0;

function notice(text:string,info=false){$('notice').textContent=text;$('notice').hidden=!text;$('notice').classList.toggle('info',info);}
function send(event:object){if(socket?.readyState!==WebSocket.OPEN)throw new Error('Connection unavailable');if(socket.bufferedAmount>256000)throw new Error('Connection is too slow. Stop and reconnect.');socket.send(JSON.stringify(event));}
function apiHeaders(){const h:Record<string,string>={'Content-Type':'application/json'};const pin=value('pin');if(pin)h['x-staff-pin']=pin;return h;}
function updateModeHelp(){const live=value('mode')==='live';$('mode-help').className='mode-help '+(live?'live':'demo');$('mode-help').innerHTML=live?'<strong>Live microphone</strong> records your selected microphone and sends audio to Gemini for transcription and translation. After starting, press a speaker’s microphone button below.':'<strong>Guided rehearsal</strong> does not use microphones. Start the session, then press Play next turn to run the four scripted examples.';document.querySelector<HTMLElement>('.rehearsal')!.hidden=live;}
function showView(name:'intake'|'conversation'|'review'|'history'){
 document.querySelectorAll<HTMLElement>('.view').forEach(v=>v.hidden=v.id!==`view-${name}`);document.querySelectorAll<HTMLButtonElement>('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===name));
 const copy:any={intake:['Patient intake','Register the patient.','Consent and required details must be recorded before interpretation begins.'],conversation:['Interpretation','Every word matters.','Live bilingual conversation with traceable clinical highlights.'],review:['Clinical review','Review before you rely.','Confirm or correct extracted information before reports are finalized.'],history:['History','Patient encounter history.','Find previous encounters and reopen completed reports.']};
 [$('crumb').textContent,$('page-title').textContent,$('page-subtitle').textContent]=copy[name];const step={intake:0,conversation:2,review:3,history:4}[name];document.querySelectorAll('.workflow span').forEach((s,i)=>s.classList.toggle('current',i===step));if(name==='history')void loadHistory();
}
document.querySelectorAll<HTMLButtonElement>('.nav').forEach(n=>n.onclick=()=>showView(n.dataset.view as any));
function readPatient():Patient|undefined{const form=$<HTMLFormElement>('intake-form');if(!form.reportValidity())return;return {fullName:value('fullName'),patientId:value('patientId'),birthOrAge:value('birthOrAge'),gender:value('gender'),language:value('language') as 'hi'|'te',phone:value('phone'),emergencyContact:value('emergencyContact'),allergies:value('allergies'),conditions:value('conditions'),medications:value('medications'),reasonForVisit:value('reasonForVisit'),doctorDepartment:value('doctorDepartment'),consent:true,room:value('room')};}
function applyPatient(p:Patient){patient=p;$('active-patient').textContent=p.fullName;$('active-id').textContent=`ID ${p.patientId} · ${p.doctorDepartment}`;$('chosen-language').innerHTML=p.language==='hi'?'HI <strong>Hindi</strong>':'TE <strong>Telugu</strong>';$('patient-language').textContent=p.language==='hi'?'Hindi · HI':'Telugu · TE';$('patient-caption').textContent=p.language==='hi'?'हर बात समझी जाए।':'ప్రతి మాట అర్థం కావాలి.';$('patient-caption').lang=p.language;controls();}
$('save-intake').onclick=()=>{const p=readPatient();if(!p)return;applyPatient(p);showView('conversation');notice('Patient registration and consent are ready. Review the language and start interpretation.',true);};
$<HTMLSelectElement>('mode').onchange=updateModeHelp;
$('change-patient').onclick=()=>{if(active){notice('End the active session before changing the patient.');return;}showView('intake');};
$('find-patient').onclick=()=>{const id=value('patientId');$<HTMLInputElement>('history-search').value=id;showView('history');};

function resetCapture(){for(const side of ['doctor','patient'] as const){capture[side]?.stop();delete capture[side];$(side+'-wave').classList.remove('active');$(side+'-state').textContent='Microphone stopped';$(side+'-talk').textContent=`◉ Start ${side} microphone`;$(side+'-talk').classList.remove('recording');}}
function stopMicrophone(side:Side){const mic=capture[side];if(!mic)return;mic.stop();delete capture[side];$(side+'-wave').classList.remove('active');$(side+'-state').textContent='Microphone stopped';$(side+'-talk').textContent=`◉ Start ${side} microphone`;$(side+'-talk').classList.remove('recording');controls();}
function controls(){for(const id of ['mode','pin','start'])disable(id,active||starting||!patient);for(const id of ['urgent','clear','end'])disable(id,!active);for(const side of ['doctor','patient'] as const){disable(side+'-talk',!active||mode!=='live');disable(side+'-mic',!!capture[side]);}disable('demo-next',!active||mode!=='demo'||demoStep>=4);}
function signal(urgency:string,source='manual'){$('attention').className='attention card '+urgency;$('signal-title').textContent=urgency==='critical'?'Critical attention':urgency==='high'?'Attention needed':urgency==='elevated'?'Elevated intensity':'Conversation steady';$('signal-icon').textContent=urgency==='normal'?'✓':'!';$('signal-description').textContent=urgency==='normal'?'No attention flag is currently active.':`Flagged by ${source}. A clinician must confirm or dismiss this item.`;const max={normal:0,elevated:1,high:2,critical:3}[urgency as 'normal']??0;document.querySelectorAll<HTMLElement>('.signal-scale span').forEach((s,i)=>s.style.background=i<=max?(urgency==='critical'?'#a9342d':urgency==='high'?'#cc7660':urgency==='elevated'?'#d4b065':'#8bad70'):'#edf1e8');}
function renderHighlights(){$('fact-count').textContent=String(facts.length+flags.length);$('live-highlights').replaceChildren();if(!facts.length&&!flags.length){$('live-highlights').innerHTML='<p>No extracted items yet.</p>';return;}for(const item of [...flags.map(f=>({label:'Attention',value:f.reason})),...facts].slice(-8)){const p=document.createElement('p');p.textContent=`${item.label}: ${item.value}`;$('live-highlights').append(p);}}
function renderTurn(turn:any){if(turns.some(t=>t.id===turn.id))return;turns.push(turn);if(turns.length===1)$('turns').replaceChildren();const article=document.createElement('article');article.className='turn';article.id='turn-'+turn.id;const meta=document.createElement('div');meta.className='turn-meta';const name=document.createElement('strong');name.textContent=turn.speaker;const label=document.createElement('span');label.className='classification';label.textContent=turn.classification||'Statement';const time=document.createElement('span');time.textContent=new Date(turn.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});meta.append(name,label,time);if(turn.urgency!=='normal'){const flag=document.createElement('span');flag.className=turn.urgency;flag.textContent=turn.urgency.toUpperCase()+' ATTENTION';meta.append(flag);}const original=document.createElement('p');original.className='original';original.textContent=turn.original_text;const translated=document.createElement('p');translated.textContent=turn.translated_text;article.append(meta,original,translated);$('turns').append(article);$('turns').scrollTop=$('turns').scrollHeight;$('partial').textContent='';$('turn-count').textContent=`${turns.length} translated turns`;$(turn.speaker+'-caption').textContent=turn.original_text;if(mode==='demo'&&$<HTMLInputElement>('sound').checked&&'speechSynthesis'in window){const speech=new SpeechSynthesisUtterance(turn.translated_text);speech.lang=turn.speaker==='patient'?'en-IN':patient!.language+'-IN';speechSynthesis.speak(speech);}}
async function onEvent(event:any){
 if(event.type==='session_started'){active=true;starting=false;sessionId=event.sessionId;startTime=Date.now();$('session-id').textContent='SESSION '+sessionId.slice(0,8).toUpperCase();$('session-status').textContent='Interpretation active';$('connection').innerHTML='<i></i> '+(mode==='demo'?'Rehearsal connected':'Provider connected');$('connection').classList.add('live');notice(mode==='demo'?'Guided rehearsal is active. Play each scripted turn.':'Live session ready. Start one microphone at a time or use separate inputs.',true);controls();}
 if(event.type==='transcript_update')$(event.speaker+'-caption').textContent=event.text;if(event.type==='translation_update')$('partial').textContent=event.text;if(event.type==='translated_turn')renderTurn(event);
 if(event.type==='clinical_update'){facts.push(...event.facts);flags.push(...event.flags);renderHighlights();if(event.flags.length)signal(event.flags[0].level,'explicit language');}
 if(event.type==='urgency_update')signal(event.urgency,event.source);if(event.type==='interrupt'){playback.doctor.stop();playback.patient.stop();window.speechSynthesis?.cancel();}
 if(event.type==='audio_output'&&active&&$<HTMLInputElement>('sound').checked){const recipient=event.speaker==='doctor'?'patient':'doctor';const queuedMs=await playback[recipient as Side].play(event.audio,event.mime_type)||0;captureMutedUntil=Math.max(captureMutedUntil,performance.now()+queuedMs+120);notice('Translation is playing. Microphone capture stays on and resumes automatically after playback.',true);}if(event.type==='error')notice(event.message);
 if(event.type==='session_ended'){active=false;resetCapture();controls();$('session-status').textContent='Awaiting clinician review';notice(`Session complete · ${event.turnCount} translated turns. Review extracted information before export.`,true);await openReview(sessionId);}
}
$('start').onclick=async()=>{if(!patient||!patient.consent){notice('Register the patient and record consent first.');showView('intake');return;}starting=true;mode=value('mode');controls();notice('Connecting…',true);try{await Promise.all([playback.doctor.unlock(),playback.patient.unlock()]);turns=[];facts=[];flags=[];demoStep=0;seq.doctor=0;seq.patient=0;$('turns').innerHTML='<div class="empty"><p>Waiting for the first turn.</p></div>';renderHighlights();signal('normal');const configured=(window as any).PULSELINE_GATEWAY as string|undefined,url=configured?new URL('/ws',configured):new URL('/ws',location.href);url.protocol=url.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(url);const timeout=setTimeout(()=>{if(starting){notice('Connection timed out. Check the gateway and try again.');socket?.close();}},45000);socket.onopen=()=>send({type:'session_start',doctorLanguage:'en',patientLanguage:patient!.language,mode,pin:value('pin'),patient});socket.onmessage=e=>{void onEvent(JSON.parse(e.data)).catch(()=>notice('A session event could not be processed.'));};socket.onerror=()=>notice('Could not connect to the gateway.');socket.onclose=e=>{clearTimeout(timeout);const wasActive=active;active=false;starting=false;resetCapture();$('connection').classList.remove('live');$('connection').innerHTML='<i></i> '+(turns.length?'Session ended':'Disconnected');controls();if(e.code!==1000&&e.code!==1005)notice(`Connection ended: ${e.reason||'network interruption'}.`);else if(wasActive)notice('Session disconnected. The saved encounter remains available in history.');};}catch(error){starting=false;controls();notice(error instanceof Error?error.message:'Unable to start');}};
for(const side of ['doctor','patient'] as const){for(let i=0;i<31;i++){const bar=document.createElement('i');bar.style.height=(4+Math.sin(i*.8)**2*(20-Math.abs(15-i)))+'px';$(side+'-wave').append(bar);}$(side+'-talk').onclick=async()=>{if(capture[side]){stopMicrophone(side);return;}const other=side==='doctor'?'patient':'doctor';if(capture[other])stopMicrophone(other);playback.doctor.stop();playback.patient.stop();captureMutedUntil=0;window.speechSynthesis?.cancel();const mic=new Capture();capture[side]=mic;try{await mic.start(value(side+'-mic'),(data,level)=>{if(active&&capture[side]===mic){if(performance.now()>=captureMutedUntil)send({type:'audio_chunk',mic:side,seq:seq[side]++,data});$(side+'-wave').classList.toggle('active',level>.01);}});$(side+'-talk').textContent=`■ Stop ${side}`;$(side+'-talk').classList.add('recording');$(side+'-state').textContent='Listening · speak now';notice(`Listening to the ${side}. The microphone stays active between translated turns.`,true);}catch{mic.stop();delete capture[side];notice('Microphone unavailable. Allow access and check the selected input.');}finally{controls();}};$(side+'-output').onchange=()=>{void playback[side].sink(value(side+'-output')).catch(e=>notice(e.message));};}
$('devices').onclick=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop());const devices=await navigator.mediaDevices.enumerateDevices();for(const side of ['doctor','patient'])for(const [kind,suffix] of [['audioinput','mic'],['audiooutput','output']]){const select=$<HTMLSelectElement>(side+'-'+suffix),previous=select.value;select.replaceChildren(new Option('Default '+(suffix==='mic'?'microphone':'speaker'),''));devices.filter(d=>d.kind===kind).forEach((d,i)=>select.add(new Option(d.label||`${suffix} ${i+1}`,d.deviceId)));select.value=previous;}notice('Audio devices refreshed.',true);}catch{notice('Allow microphone access to list audio devices.');}};
$('demo-next').onclick=()=>{send({type:'demo_turn',index:demoStep});demoStep++;$('demo-step').textContent=`${demoStep} / 4`;controls();};$('urgent').onclick=()=>send({type:'flag_urgent',speaker:'patient',urgency:'high'});$('clear').onclick=()=>send({type:'flag_urgent',speaker:'patient',urgency:'normal'});$('end').onclick=()=>{resetCapture();send({type:'session_end'});disable('end',true);};$('sound').onchange=()=>{if(!$<HTMLInputElement>('sound').checked){playback.doctor.stop();playback.patient.stop();window.speechSynthesis?.cancel();}};

function renderReview(){if(!reviewRecord)return;$('review-patient').textContent=reviewRecord.patient.fullName;$('review-id').textContent=`${reviewRecord.patient.patientId} · ${reviewRecord.sessionId.slice(0,8)}`;facts=reviewRecord.facts||[];flags=reviewRecord.flags||[];const render=(root:string,items:any[],isFlag=false)=>{const box=$(root);box.replaceChildren();if(!items.length){box.innerHTML='<div class="empty"><p>No items detected.</p></div>';return;}items.forEach((item,i)=>{const el=document.createElement('article');el.className='review-item';const title=isFlag?item.reason:item.label;el.innerHTML=`<header><strong>${escapeHtml(title)}</strong><span>${escapeHtml(isFlag?item.level:item.category)} · ${escapeHtml(item.source||item.detectionSource)}</span></header><textarea aria-label="Edit item">${escapeHtml(isFlag?item.reason:item.value)}</textarea><p class="source">Original source: ${escapeHtml(item.sourceText||item.originalText||'Manual or acoustic flag; no transcript source')}</p><div class="review-controls"><select aria-label="Review status"><option value="unconfirmed">Unconfirmed</option><option value="confirmed">Confirmed</option><option value="uncertain">Uncertain</option><option value="dismissed">Dismissed</option></select><button type="button">Remove</button></div>`;const textarea=el.querySelector('textarea')!,select=el.querySelector('select')!,button=el.querySelector('button')!;select.value=item.status;textarea.oninput=()=>{if(isFlag)item.reason=textarea.value;else item.value=textarea.value;item.updatedAt=new Date().toISOString();};select.onchange=()=>item.status=select.value;button.onclick=()=>{item.status='dismissed';select.value='dismissed';el.classList.add('dismissed');};box.append(el);});};render('review-facts',facts);render('review-flags',flags,true);disable('save-review',false);$('reports').hidden=!reviewRecord.reviewedAt;}
const escapeHtml=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
async function openReview(id:string){try{const res=await fetch(`/api/encounters/${id}`,{headers:apiHeaders()});if(!res.ok)throw new Error('Encounter is not ready yet');reviewRecord=await res.json();renderReview();showView('review');}catch(e){notice(e instanceof Error?e.message:'Could not open review');}}
$('add-fact').onclick=()=>{if(!reviewRecord)return;facts.push({id:crypto.randomUUID(),category:'highlight',label:'Clinician-added item',value:'',sourceTurnId:'',sourceText:'Manually entered by clinician',source:'manual',status:'unconfirmed',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});renderReview();};
$('save-review').onclick=async()=>{const reviewedBy=value('reviewer');if(reviewedBy.length<2){notice('Enter the clinician name or staff ID before finalizing.');return;}const unresolved=[...facts,...flags].filter(x=>x.status==='unconfirmed').length;if(unresolved){notice(`Review every item first. ${unresolved} item${unresolved===1?' is':'s are'} still unconfirmed.`);return;}const res=await fetch(`/api/encounters/${reviewRecord.sessionId}/review`,{method:'PUT',headers:apiHeaders(),body:JSON.stringify({reviewedBy,facts,flags})});if(!res.ok){notice('Clinical review could not be saved.');return;}reviewRecord=await res.json();$('reports').hidden=false;notice('Clinical review finalized. Separate reports are ready.',true);};
document.querySelectorAll<HTMLButtonElement>('[data-report]').forEach(b=>b.onclick=()=>{if(!reviewRecord)return;const a=document.createElement('a');a.href=`/api/encounters/${reviewRecord.sessionId}/reports/${b.dataset.report}`;a.download='';document.body.append(a);a.click();a.remove();notice(`${b.textContent} download started. Check the browser downloads panel.`,true);});

async function loadHistory(){const request=++historyLoad,id=value('history-search');const res=await fetch('/api/encounters'+(id?'?patientId='+encodeURIComponent(id):''),{headers:apiHeaders()});if(request!==historyLoad)return;if(!res.ok){notice('Encounter history could not be loaded.');return;}const records=await res.json(),box=$('history-list');box.replaceChildren();if(!records.length){box.innerHTML='<div class="empty"><p>No matching encounters.</p></div>';return;}for(const r of records){const row=document.createElement('article');row.className='history-row';row.innerHTML=`<div><small>PATIENT</small><strong>${escapeHtml(r.patient.fullName)}</strong><span>${escapeHtml(r.patient.patientId)}</span></div><div><small>ENCOUNTER</small><strong>${new Date(r.startedAt).toLocaleString()}</strong><span>${r.turnCount} turns · ${r.factCount} items</span></div><div><small>STATUS</small><strong>${escapeHtml(r.status)}</strong><span>${r.reviewedBy?'Reviewed':'Review required'}</span></div><div class="actions"><button class="open">Open</button><button class="new">New encounter</button><button class="delete">Delete</button></div>`;row.querySelector<HTMLButtonElement>('.open')!.onclick=()=>void openReview(r.sessionId);row.querySelector<HTMLButtonElement>('.new')!.onclick=()=>{for(const key of Object.keys(r.patient))if(document.getElementById(key)&&key!=='consent')($<HTMLInputElement>(key) as any).value=r.patient[key];$<HTMLInputElement>('consent').checked=false;showView('intake');notice('Patient details loaded. Review them and obtain consent for the new encounter.',true);};row.querySelector<HTMLButtonElement>('.delete')!.onclick=async()=>{if(!confirm('Delete this encounter and its reports? This cannot be undone.'))return;const response=await fetch(`/api/encounters/${r.sessionId}`,{method:'DELETE',headers:apiHeaders()});if(response.ok)void loadHistory();else notice('Encounter could not be deleted.');};box.append(row);}}
$('load-history').onclick=()=>void loadHistory();$('history-search').onkeydown=e=>{if(e.key==='Enter')void loadHistory();};
setInterval(()=>{if(active){const elapsed=Math.floor((Date.now()-startTime)/1000);$('timer').textContent=String(Math.floor(elapsed/60)).padStart(2,'0')+':'+String(elapsed%60).padStart(2,'0');}},1000);window.addEventListener('beforeunload',()=>{resetCapture();socket?.close();});
fetch('/api/config').then(r=>r.json()).then(config=>{const select=$<HTMLSelectElement>('mode');$('pin-label').hidden=!config.pinRequired;if(config.liveAvailable)select.value='live';else{select.value='demo';select.querySelector<HTMLOptionElement>('option[value="live"]')!.disabled=true;}updateModeHelp();}).catch(()=>notice('Gateway configuration unavailable.'));controls();showView('intake');updateModeHelp();
