import PDFDocument from 'pdfkit';
import { resolve } from 'node:path';
import { z } from 'zod';
import { analyzeTurns } from './clinical.js';
import type { ClinicalSummary,Patient,Turn } from './protocol.js';

const reviewSchema=z.object({chiefComplaint:z.string().max(3000),patientHighlights:z.array(z.string().max(3000)).max(50),doctorPlan:z.array(z.string().max(3000)).max(50),attentionItems:z.array(z.string().max(3000)).max(50),unresolved:z.array(z.string().max(3000)).max(50),reviewed:z.boolean(),reviewedBy:z.string().max(120).optional().default('')});
export const reportAccessSchema=z.object({type:z.enum(['patient','clinical','transcript','json']),sessionId:z.string().uuid(),reportToken:z.string().length(64).regex(/^[a-f0-9]+$/),review:reviewSchema});
export interface ReportRequest {type:'patient'|'clinical'|'transcript'|'json';patient:Patient;languages:{doctor:'en';patient:'hi'|'te'};sessionId:string;startedAt:string;endedAt?:string;turns:Turn[];review:z.infer<typeof reviewSchema>}

const green='#173f37',muted='#63766f',red='#a33b2e',line='#d9e2dc';
function nativeFont(language:'hi'|'te'){return resolve('assets/fonts',language==='hi'?'NotoSansDevanagari.ttf':'NotoSansTelugu.ttf');}
function safeName(value:string){return value.replace(/[^A-Za-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,60)||'patient';}
export function reportFilename(request:ReportRequest){const prefix=request.type==='patient'?'Patient_Summary':request.type==='clinical'?'Clinical_Handoff':request.type==='transcript'?'Bilingual_Transcript':'Encounter_Data';return `${prefix}_${safeName(request.patient.patientId)}.${request.type==='json'?'json':'pdf'}`;}
function collect(doc:PDFKit.PDFDocument){return new Promise<Buffer>((resolveBuffer,reject)=>{const chunks:Buffer[]=[];doc.on('data',c=>chunks.push(c));doc.on('end',()=>resolveBuffer(Buffer.concat(chunks)));doc.on('error',reject);});}
function header(doc:PDFKit.PDFDocument,title:string,patient:Patient,sessionId:string){doc.fillColor(green).font('Helvetica-Bold').fontSize(19).text('PulseLine',50,42);doc.fillColor(muted).font('Helvetica').fontSize(8).text('CLINICAL COMMUNICATION RECORD',50,66);doc.fillColor(green).font('Helvetica-Bold').fontSize(16).text(title,50,92);doc.moveTo(50,118).lineTo(545,118).strokeColor(line).stroke();doc.fillColor('#243b35').font('Helvetica-Bold').fontSize(10).text(patient.name,50,132);doc.font('Helvetica').fontSize(8).fillColor(muted).text(`Patient ID: ${patient.patientId}   Age: ${patient.age||'Not recorded'}   Gender: ${patient.gender||'Not recorded'}   Department: ${patient.department}`,50,148,{width:495});doc.text(`Encounter: ${sessionId}   Generated: ${new Date().toLocaleString('en-IN')}`,50,163,{width:495});doc.y=188;}
function footer(doc:PDFKit.PDFDocument){const pages=doc.bufferedPageRange();for(let i=0;i<pages.count;i++){doc.switchToPage(i);doc.moveTo(50,770).lineTo(545,770).strokeColor(line).stroke();doc.fillColor(muted).font('Helvetica').fontSize(7).text('Confidential clinical communication record - attention signals require clinician confirmation.',50,780,{width:420});doc.text(`Page ${i+1} of ${pages.count}`,470,780,{width:75,align:'right'});}}
function ensure(doc:PDFKit.PDFDocument,height=60){if(doc.y+height>750)doc.addPage();}
function title(doc:PDFKit.PDFDocument,value:string){ensure(doc,45);doc.moveDown(.7).fillColor(green).font('Helvetica-Bold').fontSize(11).text(value.toUpperCase());doc.moveTo(50,doc.y+3).lineTo(545,doc.y+3).strokeColor(line).stroke();doc.moveDown(.7);}
function text(doc:PDFKit.PDFDocument,value:string,opts:PDFKit.Mixins.TextOptions={}){ensure(doc,35);doc.fillColor('#263a35').font('Helvetica').fontSize(9).text(value||'Not recorded',{width:495,lineGap:3,...opts});doc.moveDown(.35);}
function bullet(doc:PDFKit.PDFDocument,value:string,color='#263a35'){ensure(doc,30);doc.fillColor(color).font('Helvetica').fontSize(9).text('•',55,doc.y,{continued:true}).text('  '+value,{width:488,lineGap:3});doc.moveDown(.25);}
function nativeText(doc:PDFKit.PDFDocument,value:string,language:'hi'|'te'){ensure(doc,35);doc.fillColor('#263a35').font(nativeFont(language)).fontSize(10).text(value,{width:495,lineGap:4});doc.font('Helvetica');doc.moveDown(.3);}
function reviewSummary(request:ReportRequest):ClinicalSummary{const analyzed=analyzeTurns(request.turns as Turn[]);return {...analyzed,chiefComplaint:request.review.chiefComplaint,patientHighlights:request.review.patientHighlights.map((x,i)=>({...analyzed.patientHighlights[i],id:String(i),category:'symptom',text:x,sourceTurnId:analyzed.patientHighlights[i]?.sourceTurnId||'',sourceText:analyzed.patientHighlights[i]?.sourceText||x,status:request.review.reviewed?'confirmed':'unconfirmed',speaker:'patient'})),doctorPlan:request.review.doctorPlan.map((x,i)=>({...analyzed.doctorPlan[i],id:String(i),category:analyzed.doctorPlan[i]?.category||'instruction',text:x,sourceTurnId:analyzed.doctorPlan[i]?.sourceTurnId||'',sourceText:analyzed.doctorPlan[i]?.sourceText||x,status:request.review.reviewed?'confirmed':'unconfirmed',speaker:'doctor'})),attentionItems:request.review.attentionItems.map((x,i)=>({...analyzed.attentionItems[i],id:String(i),category:'attention',text:x,sourceTurnId:analyzed.attentionItems[i]?.sourceTurnId||'',sourceText:analyzed.attentionItems[i]?.sourceText||x,status:request.review.reviewed?'confirmed':'unconfirmed',speaker:'patient'})),unresolved:request.review.unresolved,reviewed:request.review.reviewed,reviewedBy:request.review.reviewedBy,reviewedAt:request.review.reviewed?new Date().toISOString():undefined} as ClinicalSummary;}
export function structuredEncounter(request:ReportRequest){return {schemaVersion:1,patient:request.patient,encounter:{sessionId:request.sessionId,startedAt:request.startedAt,endedAt:request.endedAt,languages:request.languages},clinicalSummary:reviewSummary(request),turns:request.turns,notice:'AI-assisted communication record. Review by a licensed clinician is required.'};}

export async function generatePdf(request:ReportRequest){const doc=new PDFDocument({size:'A4',margin:50,bufferPages:true,info:{Title:reportFilename(request),Author:'PulseLine'}});const done=collect(doc);const summary=reviewSummary(request);
 header(doc,request.type==='patient'?'Patient Visit Summary':request.type==='clinical'?'Clinical Handoff Report':'Bilingual Encounter Transcript',request.patient,request.sessionId);
 if(request.type==='patient'){
  title(doc,'About this visit');text(doc,`Reason for visit: ${request.patient.reasonForVisit}`);text(doc,`Language used: ${request.languages.patient==='hi'?'Hindi':'Telugu'} with English interpretation`);
  title(doc,'What you told the care team');if(summary.patientHighlights.length)summary.patientHighlights.forEach(x=>bullet(doc,x.text));else text(doc,'No patient highlights were captured.');
  if(summary.attentionItems.length){title(doc,'Important warning information');summary.attentionItems.forEach(x=>bullet(doc,x.text,red));text(doc,'These items were highlighted for prompt clinical confirmation. Follow the care team’s instructions.');}
  title(doc,'Medicines, tests and next steps');if(summary.doctorPlan.length)summary.doctorPlan.forEach(x=>bullet(doc,x.text));else text(doc,'No medicine, investigation or follow-up instruction was captured in this conversation. Confirm your plan with the care team.');
  title(doc,'Your translated instructions');for(const turn of request.turns.filter(t=>t.speaker==='doctor')){text(doc,'Doctor said: '+turn.original_text);nativeText(doc,turn.translated_text,request.languages.patient);}
  title(doc,'Safety note');text(doc,'This summary supports communication and does not replace the clinician’s signed prescription, discharge instructions or medical record. If symptoms worsen or you have trouble breathing, severe chest pain, heavy bleeding, loss of consciousness or another emergency, seek immediate medical help.');
 }else if(request.type==='clinical'){
  title(doc,'Encounter details');text(doc,`Reason for visit: ${request.patient.reasonForVisit}`);text(doc,`Known allergies: ${request.patient.allergies||'Not recorded'}`);text(doc,`Known conditions: ${request.patient.conditions||'Not recorded'}`);text(doc,`Current medications: ${request.patient.currentMedications||'Not recorded'}`);
  title(doc,'Chief complaint');text(doc,summary.chiefComplaint||'Not captured');
  title(doc,'Patient-reported highlights');if(summary.patientHighlights.length)summary.patientHighlights.forEach(x=>bullet(doc,x.text));else text(doc,'No structured patient highlights captured.');
  title(doc,'Attention items');if(summary.attentionItems.length)summary.attentionItems.forEach(x=>bullet(doc,`${x.text} [source: ${x.sourceText}]`,red));else text(doc,'No automatic attention item captured.');
  title(doc,'Clinician plan');if(summary.doctorPlan.length)summary.doctorPlan.forEach(x=>bullet(doc,`[${x.category}] ${x.text}`));else text(doc,'No medication, investigation, procedure or follow-up plan captured.');
  title(doc,'Unresolved / verify');if(summary.unresolved.length)summary.unresolved.forEach(x=>bullet(doc,x,red));else text(doc,'No automatically identified incomplete item.');
  title(doc,'Review status');text(doc,summary.reviewed?`Reviewed by ${summary.reviewedBy||'clinician'} on ${new Date(summary.reviewedAt!).toLocaleString('en-IN')}`:'UNREVIEWED - all extracted information must be verified against the source conversation.');
 }else{
  for(const turn of request.turns){title(doc,`${turn.speaker.toUpperCase()} - ${new Date(turn.timestamp).toLocaleTimeString('en-IN')}${turn.urgency!=='normal'?' - '+turn.urgency.toUpperCase()+' ATTENTION':''}`);if(turn.speaker==='patient'){nativeText(doc,turn.original_text,request.languages.patient);text(doc,'English: '+turn.translated_text);}else{text(doc,'English: '+turn.original_text);nativeText(doc,turn.translated_text,request.languages.patient);}}
 }
 footer(doc);doc.end();return done;
}
