import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await mkdir('data/qa',{recursive:true});
try{
 await page.goto('http://localhost:8080');
 const fill=async(language,id)=>{await page.fill('#fullName','Browser Test Patient');await page.fill('#patientId',id);await page.fill('#birthOrAge','42');await page.selectOption('#gender','Female');await page.selectOption('#language',language);await page.fill('#phone','9999999999');await page.fill('#emergencyContact','Test Contact');await page.fill('#doctorDepartment','Emergency');await page.fill('#reasonForVisit','Chest pain and difficulty breathing');await page.check('#consent');await page.click('#save-intake');};
 await fill('hi','QA-HI');await page.selectOption('#mode','demo');await page.uncheck('#sound');await page.click('#start');await page.locator('#connection').filter({hasText:'Rehearsal connected'}).waitFor();for(let i=0;i<4;i++){await page.click('#demo-next');await page.waitForFunction(n=>document.querySelectorAll('.turn').length===n,i+1);}assert.equal(await page.locator('.turn').count(),4);assert.match(await page.locator('#signal-title').textContent(),/Attention|Critical/);await page.click('#end');await page.locator('#view-review').waitFor({state:'visible'});assert.ok(await page.locator('.review-item').count()>0);await page.locator('.review-item select').evaluateAll(nodes=>nodes.forEach(n=>{n.value='confirmed';n.dispatchEvent(new Event('change',{bubbles:true}));}));await page.fill('#reviewer','QA Clinician');await page.click('#save-review');await page.locator('#reports').waitFor({state:'visible'});for(const kind of ['patient','clinical','transcript','json']){const download=page.waitForEvent('download');await page.click(`[data-report="${kind}"]`);assert.ok((await download).suggestedFilename().length>5);}await page.screenshot({path:'data/qa/clinical-review.png',fullPage:true});
 await page.click('[data-view="history"]');await page.fill('#history-search','QA-HI');await page.click('#load-history');await page.locator('.history-row').first().waitFor();assert.match(await page.locator('.history-row').first().textContent(),/QA-HI/);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'data/qa/mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,checks:['required intake','consent gate','rehearsal','classification','attention','review','four reports','history','mobile layout','no JS errors']}));
}finally{await browser.close();}
